set -g default-shell "zsh"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

bind M-c attach-session -c "#{pane_current_path}"

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Status bar (Tokyo Night style)
set -g status on
set -g status-interval 1
set -g status-justify centre
set -g status-length 0

# Background color
set -g status-style bg=colour234,fg=colour137

# Left side: session name
set -g status-left-length 60
set -g status-left "#[fg=colour233,bg=colour148,bold] #S #[fg=colour148,bg=colour234,nobold]"

# Right side: date time
set -g status-right-length 60
set -g status-right "#[fg=colour235,bg=colour148] %d %b %Y #[fg=colour233,bg=colour148] %H:%M "

# Current window style
set -g window-status-current-style bg=colour148,fg=colour232,bold
set -g window-status-current-format " #I: #W "

# Other window style
set -g window-status-style fg=colour248,bg=colour234
set -g window-status-format " #I: #W "

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
